#!/bin/bash
set -o nounset
set -o pipefail
set -o errexit

arg1="${1:-}"
dname="beegfs-parity"
last_successful_timestamp_file="/opt/$dname/spool/last-gen-timestamp"
groups="store01 store02"

function usage {
echo "usage: beegfs-parity-gen --complete|--partial"
}

case $arg1 in
    -h|--help)
    usage
    exit 0
    ;;
    --partial)
    operation="partial"
    ;;
    --complete)
    operation="complete"
    ;;
    *)
    usage 1>&2
    exit 1
    ;;
esac

if [[ $EUID -ne 0 ]]; then
    echo "You need root privilege to run this program" 1>&2
    exit 1
fi
if [ "`hostname -s`" != "s10n50" ]; then
    echo "Should only run on s10n50" 1>&2
    exit 1
fi

# Make sure all necessary folders are present
mkdir --parents "/opt/$dname/run"
mkdir --parents "/opt/$dname/spool"
mkdir --parents "/opt/$dname/etc"

function check_beegfs_servers_online {
#TODO: any other ways the servers can be down?
if fhgfs-check-servers | grep -q "UNREACHABLE\|failed"; then
    return 1
fi
return 0
}

(
if flock --exclusive --nonblock 500; then
    if ! check_beegfs_servers_online; then
        echo "** Error: Not all of beegfs is available" 1>&2
        exit 1
    fi

    last_timestamp="0"
    if [ -f "$last_successful_timestamp_file" ]; then
        last_timestamp="`cat $last_successful_timestamp_file`"
    fi
    if [[ "$last_timestamp" =~ [^0-9] ]] ; then
        echo "** Error: Stored timestamp does not look like a number" 1>&2
        echo "          see: $last_successful_timestamp_file" 1>&2
        exit 1
    fi
    timestamp=`date +%s`

    if [ "$operation" == "complete" ] && [ "$last_timestamp" != "0" ]; then
        echo "** Warning: A complete run has already been done."
        echo "  If you continue all existing parity chunks will be deleted!"
        read -p "Continue? [y/N]" -n 1 -r -s reply
        echo
        if [[ $reply =~ [Yy] ]]; then
            echo "Continuing."
        else
            echo "Aborting"
            exit 1
        fi
        # Tell everyone to delete all old chunks and dbs
    fi

    for group in $groups; do
        echo `hostname -s` > /opt/$dname/run/hosts
        # We need two ranks per host so we double it up
        cat "/opt/$dname/etc/$group.hosts" "/opt/$dname/etc/$group.hosts" | sort >> "/opt/$dname/run/hosts"
        mpirun="mpirun --hostfile /opt/$dname/run/hosts"
        $mpirun ./bp-parity-gen/bp-parity-gen $operation /$group/chunks/ $last_timestamp $timestamp
    done

    echo $timestamp > $last_successful_timestamp_file
else
    echo "** Error: Can't acquire lock, is the program already running?" 1>&2
fi
) 500>"/opt/$dname/run/lock"

