#!/bin/sh

PID=$$

# Settings
DIR=""
LEVELDB=""
CACHEDIR="."

failed_params=0

# Parse params
while getopts "d:o:c:h" opt; do
        case $opt in
                d) DIR=$OPTARG ;;
                o) LEVELDB=$OPTARG ;;
                c) CACHEDIR=$OPTARG ;;
                h) failed_params=1 ;;
                *) failed_params=1 ;;
        esac
done


# Check params
if [ failed_params == 1 ] || [ $# -eq 0 ] || [ "$DIR" == "" ] || [ "$LEVELDB" == "" ]; then
        cat <<EOF
Usage:
  beegfs-chunkmap -d <directory to map> -o <leveldb output file> [-c <cache directory>]

Parameters explained:
  -d    Directory located on a BeeGFS mount
  -o    Output file containing a chunk map in leveldb format
  -c    Cache directory used for large temporary files (not located in BeeGFS mount!)
          default cache directory = "."
EOF
        exit 1
fi

PWD=`pwd`
BINDIR=${PWD}

# Change to CACHEDIR
cd ${CACHEDIR}


${BINDIR}/filelist-runner "${DIR}"


# Change to PWD
cd ${PWD}
