#!/bin/sh

PID=$$

# Args
DIR=""
LEVELDB=""
CACHEDIR="."

# Settings
THREADS=4
BEEGFSMOUNT="/faststorage"

failed_params=0

# Parse params
while getopts "d:o:c:h" opt; do
        case $opt in
                d) DIR=$OPTARG ;;
                o) LEVELDB=$OPTARG ;;
                c) CACHEDIR=$OPTARG ;;
                h) failed_params=1 ;;
                *) failed_params=1 ;;
        esac
done


# Check params
if [ failed_params == 1 ] || [ $# -eq 0 ] || [ "$DIR" == "" ] || [ "$LEVELDB" == "" ]; then
        cat <<EOF
Usage:
  beegfs-chunkmap -d <directory to map> -o <leveldb output file> [-c <cache directory>]

Parameters explained:
  -d    Directory located on a BeeGFS mount
  -o    Output file containing a chunk map in leveldb format (not located in BeeGFS mount!)
  -c    Cache directory used for large temporary files (not located in BeeGFS mount!)
          default cache directory = "."
EOF
        exit 1
fi

PWD=`pwd`
BINDIR=${PWD}

# Change to CACHEDIR
cd ${CACHEDIR}

# Create file lists
${BINDIR}/filelist-runner ${#BEEGFSMOUNT} "${DIR}"

# Get entry
#cat output.0 | fhgfs-ctl --getentryinfo --nomappings --verbose - 

# Cleanup
#rm -f ${CACHEDIR}/output.*

# Change to PWD
cd ${PWD}
